### ISSUE TITLE
Xamarin swiftruntimesupport error

### ISSUE THREAD

**Issue by SuperCorks** [Laerdal/Laerdal.Xamarin.Dfu.iOS#2]
**Describe the bug**
Hey guys, I'm encountering this error with all the versions of the iOS Nuget package now. I'm suspecting this has to do with the latest XCode update and the swiftruntimesupport library.
```
C:\Users\simon\.nuget\packages\xamarin.ios.swiftruntimesupport\0.2.0\buildTransitive\Xamarin.iOS.SwiftRuntimeSupport.targets(19,9): error MSB3073: 
The command "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/../../../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-stdlib-tool --copy --verbose --sign '4BCD3E5B0A18E70C9CEE70CB0FD095727E81B0A3' --scan-executable 'bin/iPhone/Debug/device-builds/ipad11.1-14.3/App3.iOS.app/App3.iOS' --scan-folder 'bin/iPhone/Debug/device-builds/ipad11.1-14.3/App3.iOS.app/Frameworks/' --scan-folder 'bin/iPhone/Debug/device-builds/ipad11.1-14.3/App3.iOS.app/PlugIns/' --platform 'iphoneos' --toolchain '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/../../../../../Toolchains/XcodeDefault.xctoolchain/' --destination 'bin/iPhone/Debug/device-builds/ipad11.1-14.3/App3.iOS.app/Frameworks/' --resource-destination 'bin/iPhone/Debug/device-builds/ipad11.1-14.3/App3.iOS.app/' --resource-library libswiftRemoteMirror.dylib --unsigned-destination 'obj/iPhone/Debug/device-builds/ipad11.1-14.3/SwiftSupport' --strip-bitcode --strip-bitcode-tool '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/../../../../../Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip' --emit-dependency-info 'obj/iPhone/Debug/device-builds/ipad11.1-14.3/SwiftStdLibToolInputDependencies.dep' --source-libraries '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos'" exited with code 255.
```

**To Reproduce**
1. Build an app using XCode 12.3 and this package downloaded from NuGet.
(I've tested with a new Xamarin Blank project and get the same result)
~~(I've also tested with VS for Mac, same result)~~

**Version Info**
XCode: 12.3
Laerdal.Xamarin.Dfu.iOS: 4.9.0.13 and 4.9.0.11
Visual Studio Windows: Community 2019 Version 16.8.4

**Comment by SuperCorks** [comment]
Sorry, my colleague just tested on VS for Mac and it seems like it works on his machine (same XCode version). I'll investigate further.

**Comment by framinosona** [comment]
No worries, I've seen that some people have had that behavior too on other packages after update, a reboot and some cleaning might help. Let me know if you see an improvement that I can make on the nuget side.

**Comment by framinosona** [comment]
Hey @SuperCorks , did you manage ? Also, did you manage to publish on app store ? I'm curious to see if you get the same issue as @OliverFlecke here : https://github.com/Laerdal/Laerdal.Xamarin.Dfu.iOS/issues/3

**Comment by SuperCorks** [comment]
Hey @framinosona, sorry I've been working on some other parts of the code lately. I'll take a look today.

We haven't deployed to the app store yet because we develop a custom wearable and they need us to send them a ton of documentation or a peer reviewed study that says what the wearable does before allowing the app in the store. It's quite tedious I must say.

**Comment by framinosona** [comment]
Heh yeah... Been there... 🙂 thanks for the help 🙂

**Comment by SuperCorks** [comment]
@framinosona, I'm back on this issue. Sorry for the long wait.
It appears that with the latest version of the package, Visual Studio and XCode our app builds fine now. 

I'm not sure if you made any changes but thanks for your help nonetheless and again, thank you so much for this package and it's Android counterpart with which I've had zero issues so far.

We're still running into the SwiftRuntime error described[ here (#3) ](https://github.com/Laerdal/Laerdal.Dfu.iOS/issues/3) when archiving the app (it's on the app store finally now), but I see you found workarounds so we'll give them a shot.

Cheers
